### ISSUE TITLE
bug: usuário admin finance não está conseguindo atualizar uma despesa submetida

### ISSUE THREAD

**Issue by MariaEduardaSampaio** [tauanyfeitosa/AdaTech.AIntelligence#109]
![Image](https://github.com/tauanyfeitosa/AdaTech.AIntelligence/assets/49692286/99eb49f3-065f-48a8-b6ff-450a022631f1)

**Comment by tauanyfeitosa** [comment]
![image](https://github.com/tauanyfeitosa/AdaTech.AIntelligence/assets/93644115/7566626a-b873-4afb-8503-3bd7113e84db)
